### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kraybit** [poohcom1/godot-state-machine#1]
Hello!

Very nice little code!
Is there any plans to add a license?

I believe, otherwise, it's basically illegal for others to use this code.
Which is perhaps your wish, and then you have my full respect, and you can ignore this post!

Kind regards
/Kraybit

See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by poohcom1** [comment]
Ah, thanks for the comment. I haven't actually actually been maintaining this because I'm been experimenting with a different kind of state machines recently, so I didn't expect others to actually be using it. Since you've mentioned it I'll go ahead and add one.

**Comment by kraybit** [comment]
Brilliant! : )
